name: Resale Flat Price
on: [push, workflow_dispatch]
  # Inputs the workflow accepts.
  inputs:
    model:
      description: 'What kind of model to be used? (decision tree / knn)'
      required: true
  
jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run executable bash script
        run: bash ./bash.sh
