name: Resale Flat Price
#on: [push, workflow_dispatch]
on:
  workflow_call:
    inputs:
      model:
        description: 'Which algorithm is to be used? (decision tree / knn)'
        required: true
        type: string
        
jobs:
  run-end-to-end-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run executable bash script
        run: bash ./bash.sh
